export const makerAbi = [
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"_gridFactory",
              "type":"address"
          },
          {
              "internalType":"address",
              "name":"_weth9",
              "type":"address"
          }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"address",
                      "name":"tokenA",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenB",
                      "type":"address"
                  },
                  {
                      "internalType":"int24",
                      "name":"resolution",
                      "type":"int24"
                  },
                  {
                      "internalType":"uint160",
                      "name":"priceX96",
                      "type":"uint160"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "components":[
                          {
                              "internalType":"int24",
                              "name":"boundaryLower",
                              "type":"int24"
                          },
                          {
                              "internalType":"uint128",
                              "name":"amount",
                              "type":"uint128"
                          }
                      ],
                      "internalType":"struct IGridParameters.BoundaryLowerWithAmountParameters[]",
                      "name":"orders0",
                      "type":"tuple[]"
                  },
                  {
                      "components":[
                          {
                              "internalType":"int24",
                              "name":"boundaryLower",
                              "type":"int24"
                          },
                          {
                              "internalType":"uint128",
                              "name":"amount",
                              "type":"uint128"
                          }
                      ],
                      "internalType":"struct IGridParameters.BoundaryLowerWithAmountParameters[]",
                      "name":"orders1",
                      "type":"tuple[]"
                  }
              ],
              "internalType":"struct IMakerOrderManager.InitializeParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"createGridAndInitialize",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[

      ],
      "name":"gridFactory",
      "outputs":[
          {
              "internalType":"address",
              "name":"",
              "type":"address"
          }
      ],
      "stateMutability":"view",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"uint256",
              "name":"amount0",
              "type":"uint256"
          },
          {
              "internalType":"uint256",
              "name":"amount1",
              "type":"uint256"
          },
          {
              "internalType":"bytes",
              "name":"data",
              "type":"bytes"
          }
      ],
      "name":"gridexPlaceMakerOrderCallback",
      "outputs":[

      ],
      "stateMutability":"nonpayable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"address",
                      "name":"tokenA",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenB",
                      "type":"address"
                  },
                  {
                      "internalType":"int24",
                      "name":"resolution",
                      "type":"int24"
                  },
                  {
                      "internalType":"uint160",
                      "name":"priceX96",
                      "type":"uint160"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "components":[
                          {
                              "internalType":"int24",
                              "name":"boundaryLower",
                              "type":"int24"
                          },
                          {
                              "internalType":"uint128",
                              "name":"amount",
                              "type":"uint128"
                          }
                      ],
                      "internalType":"struct IGridParameters.BoundaryLowerWithAmountParameters[]",
                      "name":"orders0",
                      "type":"tuple[]"
                  },
                  {
                      "components":[
                          {
                              "internalType":"int24",
                              "name":"boundaryLower",
                              "type":"int24"
                          },
                          {
                              "internalType":"uint128",
                              "name":"amount",
                              "type":"uint128"
                          }
                      ],
                      "internalType":"struct IGridParameters.BoundaryLowerWithAmountParameters[]",
                      "name":"orders1",
                      "type":"tuple[]"
                  }
              ],
              "internalType":"struct IMakerOrderManager.InitializeParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"initialize",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"bytes[]",
              "name":"data",
              "type":"bytes[]"
          }
      ],
      "name":"multicall",
      "outputs":[
          {
              "internalType":"bytes[]",
              "name":"results",
              "type":"bytes[]"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenA",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenB",
                      "type":"address"
                  },
                  {
                      "internalType":"int24",
                      "name":"resolution",
                      "type":"int24"
                  },
                  {
                      "internalType":"bool",
                      "name":"zero",
                      "type":"bool"
                  },
                  {
                      "internalType":"int24",
                      "name":"boundaryLower",
                      "type":"int24"
                  },
                  {
                      "internalType":"uint128",
                      "name":"amount",
                      "type":"uint128"
                  }
              ],
              "internalType":"struct IMakerOrderManager.PlaceOrderParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"placeMakerOrder",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"orderId",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenA",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenB",
                      "type":"address"
                  },
                  {
                      "internalType":"int24",
                      "name":"resolution",
                      "type":"int24"
                  },
                  {
                      "internalType":"bool",
                      "name":"zero",
                      "type":"bool"
                  },
                  {
                      "components":[
                          {
                              "internalType":"int24",
                              "name":"boundaryLower",
                              "type":"int24"
                          },
                          {
                              "internalType":"uint128",
                              "name":"amount",
                              "type":"uint128"
                          }
                      ],
                      "internalType":"struct IGridParameters.BoundaryLowerWithAmountParameters[]",
                      "name":"orders",
                      "type":"tuple[]"
                  }
              ],
              "internalType":"struct IMakerOrderManager.PlaceOrderInBatchParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"placeMakerOrderInBatch",
      "outputs":[
          {
              "internalType":"uint256[]",
              "name":"orderIds",
              "type":"uint256[]"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenA",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenB",
                      "type":"address"
                  },
                  {
                      "internalType":"int24",
                      "name":"resolution",
                      "type":"int24"
                  },
                  {
                      "internalType":"bool",
                      "name":"zero",
                      "type":"bool"
                  },
                  {
                      "internalType":"uint128",
                      "name":"amount",
                      "type":"uint128"
                  },
                  {
                      "internalType":"int160",
                      "name":"priceDeltaX96",
                      "type":"int160"
                  },
                  {
                      "internalType":"uint160",
                      "name":"priceMinimumX96",
                      "type":"uint160"
                  },
                  {
                      "internalType":"uint160",
                      "name":"priceMaximumX96",
                      "type":"uint160"
                  }
              ],
              "internalType":"struct IRelativeOrderManager.RelativeOrderParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"placeRelativeOrder",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"orderId",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[

      ],
      "name":"refundNativeToken",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"token",
              "type":"address"
          },
          {
              "internalType":"uint256",
              "name":"value",
              "type":"uint256"
          },
          {
              "internalType":"uint256",
              "name":"deadline",
              "type":"uint256"
          },
          {
              "internalType":"uint8",
              "name":"v",
              "type":"uint8"
          },
          {
              "internalType":"bytes32",
              "name":"r",
              "type":"bytes32"
          },
          {
              "internalType":"bytes32",
              "name":"s",
              "type":"bytes32"
          }
      ],
      "name":"selfPermit",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"token",
              "type":"address"
          },
          {
              "internalType":"uint256",
              "name":"nonce",
              "type":"uint256"
          },
          {
              "internalType":"uint256",
              "name":"expiry",
              "type":"uint256"
          },
          {
              "internalType":"uint8",
              "name":"v",
              "type":"uint8"
          },
          {
              "internalType":"bytes32",
              "name":"r",
              "type":"bytes32"
          },
          {
              "internalType":"bytes32",
              "name":"s",
              "type":"bytes32"
          }
      ],
      "name":"selfPermitCompatible",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"token",
              "type":"address"
          },
          {
              "internalType":"uint256",
              "name":"nonce",
              "type":"uint256"
          },
          {
              "internalType":"uint256",
              "name":"expiry",
              "type":"uint256"
          },
          {
              "internalType":"uint8",
              "name":"v",
              "type":"uint8"
          },
          {
              "internalType":"bytes32",
              "name":"r",
              "type":"bytes32"
          },
          {
              "internalType":"bytes32",
              "name":"s",
              "type":"bytes32"
          }
      ],
      "name":"selfPermitCompatibleIfNecessary",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"token",
              "type":"address"
          },
          {
              "internalType":"uint256",
              "name":"value",
              "type":"uint256"
          },
          {
              "internalType":"uint256",
              "name":"deadline",
              "type":"uint256"
          },
          {
              "internalType":"uint8",
              "name":"v",
              "type":"uint8"
          },
          {
              "internalType":"bytes32",
              "name":"r",
              "type":"bytes32"
          },
          {
              "internalType":"bytes32",
              "name":"s",
              "type":"bytes32"
          }
      ],
      "name":"selfPermitIfNecessary",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"token",
              "type":"address"
          },
          {
              "internalType":"uint256",
              "name":"amountMinimum",
              "type":"uint256"
          },
          {
              "internalType":"address",
              "name":"recipient",
              "type":"address"
          }
      ],
      "name":"sweepToken",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"uint256",
              "name":"amountMinimum",
              "type":"uint256"
          },
          {
              "internalType":"address",
              "name":"recipient",
              "type":"address"
          }
      ],
      "name":"unwrapWETH9",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[

      ],
      "name":"weth9",
      "outputs":[
          {
              "internalType":"address",
              "name":"",
              "type":"address"
          }
      ],
      "stateMutability":"view",
      "type":"function"
  },
  {
      "stateMutability":"payable",
      "type":"receive"
  }
]

export const swapAbi = [
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"_gridexGridFactory",
              "type":"address"
          },
          {
              "internalType":"address",
              "name":"_uniswapV3PoolFactory",
              "type":"address"
          },
          {
              "internalType":"address",
              "name":"_uniswapV2PoolFactory",
              "type":"address"
          },
          {
              "internalType":"address",
              "name":"_weth9",
              "type":"address"
          }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
  },
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"token",
              "type":"address"
          },
          {
              "internalType":"address",
              "name":"poolAddress",
              "type":"address"
          }
      ],
      "name":"approveToCurvePool",
      "outputs":[

      ],
      "stateMutability":"nonpayable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"bytes",
                      "name":"path",
                      "type":"bytes"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountIn",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountOutMinimum",
                      "type":"uint256"
                  }
              ],
              "internalType":"struct ISwapRouter.ExactInputParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"exactInput",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"amountOut",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"address",
                      "name":"tokenIn",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenOut",
                      "type":"address"
                  },
                  {
                      "internalType":"int24",
                      "name":"resolution",
                      "type":"int24"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountIn",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountOutMinimum",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint160",
                      "name":"priceLimitX96",
                      "type":"uint160"
                  }
              ],
              "internalType":"struct ISwapRouter.ExactInputSingleParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"exactInputSingle",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"amountOut",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"bytes",
                      "name":"path",
                      "type":"bytes"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountIn",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountOutMinimum",
                      "type":"uint256"
                  }
              ],
              "internalType":"struct ISwapRouterHub.ExactMixedInputParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"exactMixedInput",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"amountOut",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"bytes",
                      "name":"path",
                      "type":"bytes"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountOut",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountInMaximum",
                      "type":"uint256"
                  }
              ],
              "internalType":"struct ISwapRouter.ExactOutputParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"exactOutput",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"amountIn",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"address",
                      "name":"tokenIn",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenOut",
                      "type":"address"
                  },
                  {
                      "internalType":"int24",
                      "name":"resolution",
                      "type":"int24"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountOut",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountInMaximum",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint160",
                      "name":"priceLimitX96",
                      "type":"uint160"
                  }
              ],
              "internalType":"struct ISwapRouter.ExactOutputSingleParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"exactOutputSingle",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"amountIn",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[

      ],
      "name":"gridFactory",
      "outputs":[
          {
              "internalType":"address",
              "name":"",
              "type":"address"
          }
      ],
      "stateMutability":"view",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"int256",
              "name":"amount0Delta",
              "type":"int256"
          },
          {
              "internalType":"int256",
              "name":"amount1Delta",
              "type":"int256"
          },
          {
              "internalType":"bytes",
              "name":"_data",
              "type":"bytes"
          }
      ],
      "name":"gridexSwapCallback",
      "outputs":[

      ],
      "stateMutability":"nonpayable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"bytes[]",
              "name":"data",
              "type":"bytes[]"
          }
      ],
      "name":"multicall",
      "outputs":[
          {
              "internalType":"bytes[]",
              "name":"results",
              "type":"bytes[]"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[

      ],
      "name":"refundNativeToken",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"token",
              "type":"address"
          },
          {
              "internalType":"uint256",
              "name":"value",
              "type":"uint256"
          },
          {
              "internalType":"uint256",
              "name":"deadline",
              "type":"uint256"
          },
          {
              "internalType":"uint8",
              "name":"v",
              "type":"uint8"
          },
          {
              "internalType":"bytes32",
              "name":"r",
              "type":"bytes32"
          },
          {
              "internalType":"bytes32",
              "name":"s",
              "type":"bytes32"
          }
      ],
      "name":"selfPermit",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"token",
              "type":"address"
          },
          {
              "internalType":"uint256",
              "name":"nonce",
              "type":"uint256"
          },
          {
              "internalType":"uint256",
              "name":"expiry",
              "type":"uint256"
          },
          {
              "internalType":"uint8",
              "name":"v",
              "type":"uint8"
          },
          {
              "internalType":"bytes32",
              "name":"r",
              "type":"bytes32"
          },
          {
              "internalType":"bytes32",
              "name":"s",
              "type":"bytes32"
          }
      ],
      "name":"selfPermitCompatible",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"token",
              "type":"address"
          },
          {
              "internalType":"uint256",
              "name":"nonce",
              "type":"uint256"
          },
          {
              "internalType":"uint256",
              "name":"expiry",
              "type":"uint256"
          },
          {
              "internalType":"uint8",
              "name":"v",
              "type":"uint8"
          },
          {
              "internalType":"bytes32",
              "name":"r",
              "type":"bytes32"
          },
          {
              "internalType":"bytes32",
              "name":"s",
              "type":"bytes32"
          }
      ],
      "name":"selfPermitCompatibleIfNecessary",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"token",
              "type":"address"
          },
          {
              "internalType":"uint256",
              "name":"value",
              "type":"uint256"
          },
          {
              "internalType":"uint256",
              "name":"deadline",
              "type":"uint256"
          },
          {
              "internalType":"uint8",
              "name":"v",
              "type":"uint8"
          },
          {
              "internalType":"bytes32",
              "name":"r",
              "type":"bytes32"
          },
          {
              "internalType":"bytes32",
              "name":"s",
              "type":"bytes32"
          }
      ],
      "name":"selfPermitIfNecessary",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"address",
              "name":"token",
              "type":"address"
          },
          {
              "internalType":"uint256",
              "name":"amountMinimum",
              "type":"uint256"
          },
          {
              "internalType":"address",
              "name":"recipient",
              "type":"address"
          }
      ],
      "name":"sweepToken",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"uint256",
              "name":"amountIn",
              "type":"uint256"
          },
          {
              "internalType":"uint256",
              "name":"amountOutMinimum",
              "type":"uint256"
          },
          {
              "internalType":"address[]",
              "name":"path",
              "type":"address[]"
          },
          {
              "internalType":"address",
              "name":"to",
              "type":"address"
          }
      ],
      "name":"uniswapV2ExactInput",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"amountOut",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"uint256",
              "name":"amountOut",
              "type":"uint256"
          },
          {
              "internalType":"uint256",
              "name":"amountInMaximum",
              "type":"uint256"
          },
          {
              "internalType":"address[]",
              "name":"path",
              "type":"address[]"
          },
          {
              "internalType":"address",
              "name":"to",
              "type":"address"
          }
      ],
      "name":"uniswapV2ExactOutput",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"amountIn",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[

      ],
      "name":"uniswapV2PoolFactory",
      "outputs":[
          {
              "internalType":"address",
              "name":"",
              "type":"address"
          }
      ],
      "stateMutability":"view",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"bytes",
                      "name":"path",
                      "type":"bytes"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountIn",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountOutMinimum",
                      "type":"uint256"
                  }
              ],
              "internalType":"struct IUniswapV3Router.UniswapV3ExactInputParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"uniswapV3ExactInput",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"amountOut",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"address",
                      "name":"tokenIn",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenOut",
                      "type":"address"
                  },
                  {
                      "internalType":"uint24",
                      "name":"fee",
                      "type":"uint24"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountIn",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountOutMinimum",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint160",
                      "name":"sqrtPriceLimitX96",
                      "type":"uint160"
                  }
              ],
              "internalType":"struct IUniswapV3Router.UniswapV3ExactInputSingleParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"uniswapV3ExactInputSingle",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"amountOut",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"bytes",
                      "name":"path",
                      "type":"bytes"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountOut",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountInMaximum",
                      "type":"uint256"
                  }
              ],
              "internalType":"struct IUniswapV3Router.UniswapV3ExactOutputParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"uniswapV3ExactOutput",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"amountIn",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "components":[
                  {
                      "internalType":"address",
                      "name":"tokenIn",
                      "type":"address"
                  },
                  {
                      "internalType":"address",
                      "name":"tokenOut",
                      "type":"address"
                  },
                  {
                      "internalType":"uint24",
                      "name":"fee",
                      "type":"uint24"
                  },
                  {
                      "internalType":"address",
                      "name":"recipient",
                      "type":"address"
                  },
                  {
                      "internalType":"uint256",
                      "name":"deadline",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountOut",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint256",
                      "name":"amountInMaximum",
                      "type":"uint256"
                  },
                  {
                      "internalType":"uint160",
                      "name":"sqrtPriceLimitX96",
                      "type":"uint160"
                  }
              ],
              "internalType":"struct IUniswapV3Router.UniswapV3ExactOutputSingleParameters",
              "name":"parameters",
              "type":"tuple"
          }
      ],
      "name":"uniswapV3ExactOutputSingle",
      "outputs":[
          {
              "internalType":"uint256",
              "name":"amountIn",
              "type":"uint256"
          }
      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[

      ],
      "name":"uniswapV3PoolFactory",
      "outputs":[
          {
              "internalType":"address",
              "name":"",
              "type":"address"
          }
      ],
      "stateMutability":"view",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"int256",
              "name":"amount0Delta",
              "type":"int256"
          },
          {
              "internalType":"int256",
              "name":"amount1Delta",
              "type":"int256"
          },
          {
              "internalType":"bytes",
              "name":"_data",
              "type":"bytes"
          }
      ],
      "name":"uniswapV3SwapCallback",
      "outputs":[

      ],
      "stateMutability":"nonpayable",
      "type":"function"
  },
  {
      "inputs":[
          {
              "internalType":"uint256",
              "name":"amountMinimum",
              "type":"uint256"
          },
          {
              "internalType":"address",
              "name":"recipient",
              "type":"address"
          }
      ],
      "name":"unwrapWETH9",
      "outputs":[

      ],
      "stateMutability":"payable",
      "type":"function"
  },
  {
      "inputs":[

      ],
      "name":"weth9",
      "outputs":[
          {
              "internalType":"address",
              "name":"",
              "type":"address"
          }
      ],
      "stateMutability":"view",
      "type":"function"
  },
  {
      "stateMutability":"payable",
      "type":"receive"
  }
]